// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3w-CM32p3pqul9Ucc8nS4n62sYrKyFoU',
    appId: '1:776937770544:web:2a149f4b8f56848a56a7f5',
    messagingSenderId: '776937770544',
    projectId: 'itemy-63118',
    authDomain: 'itemy-63118.firebaseapp.com',
    storageBucket: 'itemy-63118.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXLKwu-s1T42oD7mCuzGQJ9aVb_YzpYQ',
    appId: '1:776937770544:android:72ef7675e7e5fbee56a7f5',
    messagingSenderId: '776937770544',
    projectId: 'itemy-63118',
    storageBucket: 'itemy-63118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi2gW37zdbkase8nofsHTKUTL9tweuWvM',
    appId: '1:776937770544:ios:f8c44997ae4c9d1c56a7f5',
    messagingSenderId: '776937770544',
    projectId: 'itemy-63118',
    storageBucket: 'itemy-63118.firebasestorage.app',
    iosBundleId: 'com.example.itemyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi2gW37zdbkase8nofsHTKUTL9tweuWvM',
    appId: '1:776937770544:ios:f8c44997ae4c9d1c56a7f5',
    messagingSenderId: '776937770544',
    projectId: 'itemy-63118',
    storageBucket: 'itemy-63118.firebasestorage.app',
    iosBundleId: 'com.example.itemyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3w-CM32p3pqul9Ucc8nS4n62sYrKyFoU',
    appId: '1:776937770544:web:2a149f4b8f56848a56a7f5',
    messagingSenderId: '776937770544',
    projectId: 'itemy-63118',
    authDomain: 'itemy-63118.firebaseapp.com',
    storageBucket: 'itemy-63118.firebasestorage.app',
  );
}
